In [87]:
###########CODE
import math
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.decomposition import TruncatedSVD

from sklearn import datasets
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse
import matplotlib.transforms as transforms

from sklearn.decomposition import PCA
from sklearn.decomposition import TruncatedSVD
from mpl_toolkits import mplot3d
import pandas as pd

from matplotlib import animation
from IPython.display import HTML


# GRADIENT 
LINK https://www.symbolab.com/solver/gradient-calculator/gradient%20x%5E%7B2%7D%2By%5E%7B2%7D?or=input

In [ ]:
def f(a, b): 
    #### Tutaj wpisz swoja funkcje w nomralnej formie
    return 1/4 * (25-a**2 * b**2)**2 + 1/2 * a**2 + 1/2 * b**2  

def grad_f(a,b): 
    #### Wpisz pochodna z respektem do a
    grad_a = (25-a**2*b**2)*-b**2*a+a
    #### Wpisz pochodna z respektem do b
    grad_b = (25-a**2*b**2)*-b*a**2+b
    return grad_a, grad_b

def gradient_descent(f, grad_f, eta, x_0, max_iter):
    ### Podaaj funkcje f bez wartosci , funkcje grad_f bez wartosci ,eta jako wielkosc twojego stepu,
    ### x_0 to punkt startowy w formie listy, i ilosc iteracji
    x = x_0
    for i in range(max_iter):
        x_a, x_b = grad_f(*x)
        x_a = x[0] - eta * x_a
        x_b = x[1] - eta * x_b
        x = x_a, x_b
    return x


In [56]:
### Podaaj funkcje f bez wartosci , funkcje grad_f bez wartosci ,eta jako wielkosc twojego stepu,
### x_0 to punkt startowy w formie listy, i ilosc iteracji
g=gradient_descent(f,grad_f,0.01,[1,1],3)

#funkcja od grad
f(*g)

24.330856546423522

# COORDINATE DESCENT

In [57]:
# dajesz x startowe y startowe i ilosc iteracji
def cor(x,y,max_iter): 
    for i in range(max_iter):
        # NAPISZ POCHODNA OD X, PRZYROWNAJ DO 0 , WYCIAGNIJ X (X=...)
        x=20*y/(2*y**2+0.2) 
        
        # NAPISZ POCHODNA OD Y, PRZYROWNAJ DO 0, WYCIAGNIJ Y (Y=...)
        y=20*x/(2*x**2+0.2) 
    return x,y
def f_cor(x,y):
    #### WPISZ SWOJA FUNKCJE
    return x*y

a=cor(1,1,3)
f_cor(*a)

# ENTROPY
https://planetcalc.com/2476/

1. Dla klasy
Patrzymy tylko na outcome i podajemy do naszej funkcji prawdopodobienstwo outcome'u

2. Dla splitu (np. weather=sunny)
To samo ale tylko bierzemy outcome'y dla weather=sunny

In [58]:
#### Policz prawdopodpienstwo na wartosci y , tutaj zakladamy ze sa 2 mozliwosci 
def Entropy(P_0,P_1):
    P_0 = -1*P_0 *math.log2(P_0)
    P_1  = -1*P_1 *math.log2(P_1)
    return P_0 +P_1


# GINI
**Information Gain** for the split of a node $m$, whose entropy measure of its parent $m-1$ is $Q(R_{m-1})$ is defined as:  $$IG(R_{m-1},R_{m}) = Q(R_{m-1}) - Q(R_{m}).$$ 

<br>

|Example| Outlook | Weekend |  Humidity | Wind | Temperature | Played Football?  |  
|:----:|:------:|:-----:|:-----:|:-----:|:-----:|:-----:|
|1| Sunny | Y | Normal | Weak | 24 | Y | 
|2| Sunny | N | Normal | Strong | 18 | Y | 
|3| Sunny | Y | Normal | Strong | 30 | Y | 
|4| Overcast | N | High | Strong| 20 | N | 
|5| Rainy | N | Normal | Weak | 21 | N | 
|6| Sunny | Y| Normal | Strong | 16 | N | 

<br>


$$Q(R; Outlook,\ Sunny) = \frac{2}{3}\left[\frac{3}{4}\cdot\frac{1}{4}+\frac{1}{4}\cdot\frac{3}{4}\right] +
                               \frac{1}{3} \cdot 0 = 0.125.$$

# FIT POLYNOMIAL DEGREE $k = 2$
$k=2\implies x^2$

In [59]:


X=[-1,0,2,3]
Y=[2,-1,3,4]
p_fitted= np.polyfit(X,Y,deg=2)
p_fitted
### osattni to intercept

array([ 0.66666667, -0.53333333,  0.2       ])

# 2-RANK FACTORIZATION

In [60]:
def rankRsvd(D, rank):
    cp = D.copy()
    U, s, Vt = np.linalg.svd(cp, full_matrices=True)
    Y = U[:,:rank]*np.sqrt(s[:rank])
    X = Vt.T[:, :rank] * np.sqrt(s[:rank])
    return Y@X.T

D= np.array([[4,5,1,2],
             [5,4,5,3],
             [5,3,1,2],
             [1,2,5,1],
             [3,1,5,1]])
U, s, Vt = np.linalg.svd(D,full_matrices=True)

r = 2 # rank
X = Vt.T[:,0:r]*np.sqrt(s[0:r])
Y = U[:,0:r]*np.sqrt(s[0:r])

In [61]:
# 1 to do ilu decymali zaokraglic
np.round(Y@X.T,1)

array([[4.7, 4.1, 0.9, 2.2],
       [5.1, 4.2, 5. , 2.6],
       [4.3, 3.8, 1.1, 2. ],
       [1.7, 1.2, 4.9, 1. ],
       [2.3, 1.7, 5. , 1.3]])

# PCA

In [62]:
D = np.array([[1, 2, 1],
        [0, 1, 2],
        [3, 1, 2],
        [3, 3, 1]])

In [ ]:
#below switch to n_components 1 for answers for Q25 of final practice

In [92]:
pca = PCA(n_components=2)
pca.fit(D)
pcs = pca.components_.T
pc1=pcs[:,0]
x=D@pc1
x


array([-1.51545959, -0.06749765, -2.80255338, -3.71884709])

In [93]:
np.var(x)

1.8912873351042705

# SAMPLE VARIANCE OF A FEATURE

In [94]:
import math

α = np.array([1/3,2/3, 2/3])
α=α/np.linalg.norm(α)

D2 = [[1, 0, 1], [0, 1, 2], [4, 1, 2]]
D_a = D2@α
print(D_a)
np.var(D_a)

[1.         2.         3.33333333]


0.91358024691358